config/routes.rb
Rails.application.routes.draw do
  root "homes#index" 
  
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'             
      }
      devise_scope :user do  
        get '/users/employee_new', :to => 'users/registrations#employee_new'
        post '/users/employee_create',:to => 'users/registrations#employee_create'
      end
    #devise_for :users, controllers: { registrations: 'registrations' }
    # resources :companies, only: [:new, :create]
    #Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    #Defines the root path route ("/")
    # root "articles#index"

  resources :customers
  # resources :companies do 
  #   # get '/companies/:id', to: 'companies#dashboard'
  #    #get 'dashboard', to: 'companies#dashboard', on: :member
  # end

  resources :companies  do 
    collection do
      get 'dashboard'
    end
    resources :employees
    resources :products
  end
   
  # resources :companies  do 
  # end
  #resources :companies
  # resources :companies do
  # end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company

  validates :name,:email,:contact,  presence: true
  validates :contact, numericality:{ only_integer: true, message: "Only integer values are allowed"},
                                  length: { is: 10, message: "number must be exactly 10 digits" }
  validates :name,format:{with:/\A[a-zA-Z ]+\z/,message:"only allows letters" }
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_company, only:[:index,:new,:create,:show,:edit,:update,:destroy]
  before_action :set_employee,  only:[:show,:edit,:update,:destroy]

 
  def index
    @employees = @company.employees.all
  end
  
  def new 
    @employee = @company.employees.new
  end

  def create
    @employee = @company.employees.create(employee_params)
      if @employee.save
        flash[:notice] = "Employee was successfully created"
        redirect_to company_employees_path(@company)
      else
        render  :new, status: :unprocessable_entity 
      end
  end

  def show
  end

  def edit
  end

  def update
    if@employee.update(employee_params)
      flash[:notice] = "Employee was successfully update"
      redirect_to company_employee_path(@company,@employee)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy 
    @employee.destroy
    flash[:notice] = "Employee was successfully Deleted"
    redirect_to company_employees_path
  end



  private
    def set_employee 
      @employee = @company.employees.find(params[:id])
    end   
 
    def employee_params
      params.require(:employee).permit(:name,:email,:contact)
    end

    def fetch_company
      @company = Company.find(params[:company_id])
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with model: [company, employee] do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @employee.errors.full_messages_for(:name).each do |message| %>
      <div class="text-danger"><%=message %></div>
    <%end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
    <% @employee.errors.full_messages_for(:email).each do |message| %>
      <div class="text-danger"><%= message %></div>
    <%end %>
  </div>

  <div>
    <%= form.label :contact %><br>
    <%= form.telephone_field :contact %>
    <% @employee.errors.full_messages_for(:contact).each do |message| %>
      <div class="text-danger"><%=message %></div>
    <%end %>
  </div>

  <div class="mt-3"> 
    <%= form.submit "Update",class:"btn btn-outline-primary"%>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h2>This is the update page </h2>
<%= render 'form', company: @company, employee: @employee %>

app/views/employees/index.html.erb
<div class="card">
  <div class="card-header p-1">
    <h3 class="card-title mb-0"> Employees_table </h3>
  </div>

  <style>
  </style>

  <div class="card-body p-0">
    <table class="table table-hover table-sm mb-0">
      <thead>
        <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Contact</th>
        <th colspan="3">Action</th> 
        </tr>
      </thead>
      <tbody>
        <% @employees.each do |employee| %>
          <tr>
          <td><%= link_to employee.name, company_employee_path(@company, employee.id),class:"employee" %></td>
          <td> <%= employee.email%> </td>
          <td> <%= employee.contact %> </td>
          <td><%= link_to "Edit",edit_company_employee_path(@company,employee.id),class:"btn btn-outline-success px-2 py-0 "%></td>
          </tr>
        <%end %>  
      </tbody>
    </table>
  </div>

  <div class="card-footer m-0">
    <div class="mt-0">
      <%= link_to 'New Employee',new_company_employee_path(@company),class:"btn btn-outline-primary"%>
      <%= link_to "Back Company",company_path(@company),class:"btn btn-outline-primary" %>
    </div>
  </div>

    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
</div>

app/views/employees/new.html.erb
<h1> Create employee</h1>

<%= form_with model: [@company,@company.employees.build] do  |form| %>

  <div>
    <%= form.label :name %> <br>
    <%= form.text_field :name %>
    <% @company.employees.each do |employee| %>
    <% employee.errors.full_messages_for(:name).each do |message| %>
      <div class="text-danger"><%= message %></div>
      <% end %>
    <% end %>
  </div>

  
  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
     <% @company.employees.each do |employee| %>
    <% employee.errors.full_messages_for(:email).each do |message| %>
      <div class="text-danger"><%= message %></div>
      <% end %>
    <% end %>
  </div>

  
  <div>
    <%= form.label :contact %><br>
    <%= form.telephone_field :contact%> 
    <% @company.employees.each do |employee| %>
    <% employee.errors.full_messages_for(:contact).each do |message| %>
    <div class="text-danger"><%= message %></div>
    <% end %>
    <% end %>
  </div>

  <div class="mt-3">
    <%= form.submit "Create",class: "btn btn-outline-primary" %>
  </div>
 <% end %>

app/views/employees/show.html.erb
<div class="card">
  <div class="card-header">
  <h3 class="card-title mb-0">Empolyee Details</h3>
  </div>

  <style>
    {
    width: 50%;
    }
  </style>

  <div class="card-body p-0">
    <table class="table table-hover table-sm mb-0">
    <tbody>
    <div>
      <tr>
      <th><strong>Name:</strong></th>
      <td> <%= @employee.name%></td>
      </tr>
    </div>

    <div>
      <tr>
      <th><strong>Email:</strong></th>
      <td><%=@employee.email %> </td>
      </tr>
    </div>

    <div>
      <tr>
      <th><strong>Contact:</strong></th>
      <td><%=@employee.contact %></td>
      </tr>
    </div>
    </tbody>
    </table>
  </div>

  <div class="card-footer">
    <div>
      <%= link_to "Back",company_employees_path(@company,@employee),class:"btn btn-outline-primary" %>
      <%= link_to "Edit",edit_company_employee_path(@company,@employee),class:"btn btn-outline-primary" %>
    </div>

    <div class="mt-2  ">
      <td> <%= link_to "Delete", company_employee_path(@company,@employee), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?" },class:"btn btn-outline-danger" %> </td>
    </div>
  
  <% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
  <% end %>
</div>  