config/routes.rb
Rails.application.routes.draw do
  root "homes#index" 
  
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'             
      }
      devise_scope :user do  
        get '/users/employee_new', :to => 'users/registrations#employee_new'
        post '/users/employee_create',:to => 'users/registrations#employee_create'
      end
    #devise_for :users, controllers: { registrations: 'registrations' }
    # resources :companies, only: [:new, :create]
    #Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    #Defines the root path route ("/")
    # root "articles#index"

  resources :customers
  # resources :companies do 
  #   # get '/companies/:id', to: 'companies#dashboard'
  #    #get 'dashboard', to: 'companies#dashboard', on: :member
  # end

  resources :companies  do 
    collection do
      get 'dashboard'
    end
    resources :employees
    resources :products
  end
   
  # resources :companies  do 
  # end
  #resources :companies
  # resources :companies do
  # end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_and_belongs_to_many :companies 



  #validates 
  validates :name, presence: true 
  validates :name, format:{with:/\A[a-zA-Z ]+\z/,message:"only allows letters" }
  validates :contact, presence: true, numericality:{ only_integer: true, message: "Only integer values are allowed"},
                                  length: { is: 10, message: "number must be exactly 10 digits" }
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    
  def index
    @customers = Customer.all
  end
  def new
    @companies = Company.all
    # com = Company.find(params[:id])
    @customer = Customer.new
    # customer = com.customers.new
  end

  def create

    # @customer = Customer.new(customer_params)    
    company = Company.find(params[:customer][:comapnies_ids])
  
    @customer = Customer.new(customer_params)
    if @customer.save
      company.customers << @customer
      redirect_to customers_path
    else
      @companies = Company.all
      render :new, status: :unprocessable_entity
    end
  end

  private
    def customer_params
      params.require(:customer).permit(:name, :contact)
      #@customer.company_ids = params[:customer][:company_ids]
    end
end

#@customer.company_ids = params[:customer][:company_ids]

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/index.html.erb
<div class="card">
  <div class="card-header p-1">
    <h3 class="card-title mb-0"> customer_table </h3>
  </div>

  <style>
  </style>

  <div class="card-body p-0">
    <table class="table table-hover table-sm mb-0">
      <thead>
        <tr>
        <th>Name</th>
        <th>Contact</th>
        <th colspan="3">Action</th> 
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
          <td><%=customer.name %></td>
          <td> <%=customer.contact %> </td> 
          </tr>
        <%end %>  
      </tbody>
    </table>
  </div>
<div class="card-footer p-0">
  <%= link_to "Create",new_customer_path,class:"btn btn-outline-primary"%>
</div>
</div>

app/views/customers/new.html.erb
<%= form_with model: @customer do |form| %>

  <div>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
  <% @customer.errors.full_messages_for(:name).each do |message| %>
      <div class="text-danger"><%= message %></div>
    <% end %>
  </div>
  
  <div>
  <%= form.label :contact %><br>
  <%= form.telephone_field :contact %>
  <% @customer.errors.full_messages_for(:contact).each do |message| %>
      <div class="text-danger"><%= message %></div>
    <% end %>
  </div>

  <h3>Select Company</h3>
  <div class = "field">
    <%#= form.label :company_id, "Select Companies" %>
    <%= form.collection_select :comapnies_ids, Company.all, :id, :name, multiple: true  %>
    <%#= form.select :company_id, options_for_select(@companies.map { |c| [c.name, c.id] }, @customer.company_ids), include_blank: true  %>
  </div>
   
  <div class="mt-3">
    <%= form.submit "Submit",class:"btn btn-outline-primary" %>
  </div>
<% end %>