config/routes.rb
Rails.application.routes.draw do
  root "homes#index" 
  
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'             
      }
      devise_scope :user do  
        get '/users/employee_new', :to => 'users/registrations#employee_new'
        post '/users/employee_create',:to => 'users/registrations#employee_create'
      end
    #devise_for :users, controllers: { registrations: 'registrations' }
    # resources :companies, only: [:new, :create]
    #Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    #Defines the root path route ("/")
    # root "articles#index"

  resources :customers
  # resources :companies do 
  #   # get '/companies/:id', to: 'companies#dashboard'
  #    #get 'dashboard', to: 'companies#dashboard', on: :member
  # end

  resources :companies  do 
    collection do
      get 'dashboard'
    end
    resources :employees
    resources :products
  end
   
  # resources :companies  do 
  # end
  #resources :companies
  # resources :companies do
  # end
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :products
  has_many :employees, :dependent => :destroy
  accepts_nested_attributes_for :employees
  has_and_belongs_to_many :customers
  has_many :users 
  
  #validates
  validates :name ,presence: true
  validates :owner_name,:address,  presence: true
  validates :name,:owner_name,:address,  format:{with:/\A[a-zA-Z ]+\z/,message:"only allows letters" }

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only:[:show,:edit,:update,:destroy]

 
  def index
    @companys  = Company.all
  end

  def new
    @company = Company.new
  end
 
  def create
    @company = Company.create(company_params)
     authorize @company
    if @company.save
      flash[:notice] = "company was successfully created"
      redirect_to companies_path 
    else
      #render :new,  status: :unprocessable_entity 
    end
  end

  def show 
  end

  def edit
    @company = Company.find(params[:id])
    authorize @company
  end

  def update
    authorize @company
    if @company.update(company_params)
    flash[:notice] = "company was seccessfully updated"
    redirect_to dashboard_companies_path
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
     
    @company.destroy
    flash[:notice] = "company was seccessfully deleted"
       redirect_to companies_path 
  end
  
  def dashboard
   @company = current_user.company
    # @user = User.find(params[:id])
     #@company = @user.company
    # @products = @company.products
    # @employees = @company.employees
  end


  private
    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:name,:owner_name,:address)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with model: @company do  |form| %>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @company.errors.full_messages_for(:name).each do |message| %>
    <div class="text-danger"><%= message %> </div>
      <% end %>
  </div>

  <div>
    <%= form.label :owner_name %><br>
    <%= form.text_field :owner_name %>
    <% @company.errors.full_messages_for(:owner_name).each do |message| %>
    <div class="text-danger"><%= message %> </div>
      <% end %>
  </div>

  <div>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
    <% @company.errors.full_messages_for(:address).each do |message| %>
    <div class="text-danger"> <%= message %> </div>
      <% end %>
  </div>

  <div class="mt-3">
    <%= form.submit "update",class:"btn btn-outline-primary"%>
  </div>
 <% end %>

app/views/companies/dashboard.html.erb
<h3>Welcome to <%= @company.name %> Dashboard</h3>


<ul>
  <%= link_to "product", company_products_path(@company),class:"btn btn-outline-success"%>
  <%= link_to "employee",company_employees_path(@company),class:"btn btn-outline-success"%>
</ul>

<div class="flash-alert">
  <%= flash[:alert] %>
</div>

app/views/companies/edit.html.erb
<h2>Company Edit</h2>

<%= render "form" %>

app/views/companies/index.html.erb
<!-- <div class="container"> -->
  <div class="card">
  <div class="card-header">
    <h3 class="card-title mb-0">Companies</h3>
  </div>

  <style>
  </style>
  
  <div class="card-body p-0">
  <table class="table table-hover table-sm mb-0">
    <thead>
      <tr>
      <th>Name </th>
      <th>Owne_name</th>
      <th>Address</th>
      <th colspan="3">Action</th>
      </tr>
    </thead>
      <tbody>
        <% @companys.each do |company| %>
          <tr>
          <td> <%= link_to company.name, company_path(company)%> </td>
          <td> <%= company.owner_name %> </td>
          <td> <%= company.address %> </td>
          <td> <%= link_to "Edit",edit_company_path(company),class:" btn btn-outline-success px-2 py-0"%>
            <%= link_to "Delete", company, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"},class:"btn btn-outline-danger px-2 py-0"%>
          </td>
         </tr>
        <%end %>
      </tbody>
    </table>
  </div>
     
    <div class="card-footer p-0">
    <!-- <div>
      <%= link_to 'New company',new_company_path,class:"btn btn-outline-primary"%>
    </div> -->  
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
        </div>
      <% end %>
    </div>
    </div>


<!-- </div> -->


<!-- <h2 class="bg-success">Hello World</h2> -->

app/views/companies/new.html.erb
<h1>Company Registraction</h1>

<%= form_with model: @company do  |form| %>

  <div class="from-group">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @company.errors.full_messages_for(:name).each do |message| %>
      <div class="text-danger"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :owner_name %><br>
    <%= form.text_field :owner_name %>
    <% @company.errors.full_messages_for(:owner_name).each do |message| %>
    <div class="text-danger"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
    <% @company.errors.full_messages_for(:address).each do |message| %>
    <div class="text-danger"><%= message %></div>
    <% end %>
  </div>

  <%= form.fields_for :users do |user_fields| %>
      <%= user_fields.label :email %><br>
      <%= user_fields.email_field :email %><br>

      <%= user_fields.label :password %><br>
      <%= user_fields.password_field :password %>

      <%= user_fields.label :password_confirmation %><br>
      <%= user_fields.password_field :password_confirmation %>
      <% end %> 
  
  <div class="mt-3">
   <%= form.submit "Create company",class:" btn btn-outline-primary"%>
  </div>
  <% end %>

app/views/companies/show.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Company Details</h3>
  </div>
   <style>
   </style>
  <div class="card-body p-0">
    <table class="table table-hover table-sm table-bordered mb-0">
      <tbody>
        <tr>
          <th class="col-md-6"><strong>Name:</strong></th>
          <td class="col-md-6"><%= @company.name %></td>
        </tr>
        <tr>
          <th class="col-md-6"><strong>Owner Name:</strong></th>
          <td class="col-md-6"><%= @company.owner_name %></td>
        </tr>
        <tr>
          <th class="col-md-6"><strong>Address:</strong></th>
          <td class="col-md-6"><%= @company.address %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <div class="mt-1">
      <%= link_to "Back", companies_path, class: "btn btn-outline-primary" %> 
      <%= link_to "Edit", edit_company_path, class: "btn btn-outline-primary" %><br>
    </div>
    <div class="mt-2">
      <%= link_to "Show Employee", company_employees_path(@company), class: "btn btn-outline-primary" %>
      <%= link_to "Show Product", company_products_path(@company), class: "btn btn-outline-primary" %>
    </div>
  </div>
</div>