config/routes.rb
Rails.application.routes.draw do
  root "homes#index" 
  
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'             
      }
      devise_scope :user do  
        get '/users/employee_new', :to => 'users/registrations#employee_new'
        post '/users/employee_create',:to => 'users/registrations#employee_create'
      end
    #devise_for :users, controllers: { registrations: 'registrations' }
    # resources :companies, only: [:new, :create]
    #Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    #Defines the root path route ("/")
    # root "articles#index"

  resources :customers
  # resources :companies do 
  #   # get '/companies/:id', to: 'companies#dashboard'
  #    #get 'dashboard', to: 'companies#dashboard', on: :member
  # end

  resources :companies  do 
    collection do
      get 'dashboard'
    end
    resources :employees
    resources :products
  end
   
  # resources :companies  do 
  # end
  #resources :companies
  # resources :companies do
  # end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company

  validates :product_name, :price, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_company, only:[:index,:new,:create,:show,:edit,:update,:destroy]
  before_action :set_product, only:[:show,:edit,:update,:destroy]
  
  def index
    @products = @company.products.all
  end

  def new 
    @product = @company.products.new  
  end

  def create
    @product = @company.products.create(product_params)
    if @product.save
      flash[:notice] = "product was successfully created"
      redirect_to company_products_path(@company)
    else
      render  :new, status: :unprocessable_entity 
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:notice] = "product was successfully update"
      redirect_to company_product_path(@company,@product)
    else
      render :edit, status: :unprocessable_entity
    end 
  end

  def destroy
    @product.destroy
    flash[:notice] = "product was successfully Deleted"
    redirect_to company_products_path
  end

  private
  def set_product
    @product = @company.products.find(params[:id])
  end   

  def product_params
    params.require(:product).permit(:product_name,:price)
  end

  def fetch_company
    @company = Company.find(params[:company_id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>This is the Edit Products Details</h1>
<%= form_with model:[@company,@product] do |form| %>
<div>
  <%= form.label :product_name %><br>
  <%= form.text_field :product_name %>
</div>

<div>
  <%= form.label :price %><br>
  <%= form.number_field :price %>
</div>

<div>
  <%= form.submit %>
</div>
<% end %>

app/views/products/index.html.erb
<div class="card">
  <div class="card-header p-1">
    <h3 class="card-title mb-0">Product_table  </h3>
  </div>
  <style>
  </style>
  <div class="card-body p-0">
    <table class="table table-hover table-sm mb-0">
    <thead>
      <tr>
      <th>Product_name</th>
      <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
        <td> <%= link_to product.product_name,company_product_path(@company, product.id),class:"product" %></td>
        <td> <%= product.price%> </td>
        </tr>
        <%end %>  
    </tbody>
    </table>
  </div>


<div class="card-footer">
  <div>
    <%= link_to "NewProduct", new_company_product_path(@company),class:"btn btn-outline-success"%>
    <%= link_to "BackToCompany",company_path(@company),class:"btn btn-outline-primary" %>
  </div>
</div>

  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
    <% end %>
    </div>

<th> <%#= link_to 'View',company_product_path(@company, product.id)%></th> 
<!-- <th colspan="3">Action</th> -->

app/views/products/new.html.erb
<h1>This is new product</h1>

<%= form_with model: [@company,@company.products.build] do  |form| %>
   <div>
    <%= form.label :ProductName %><br>
    <%= form.text_field :product_name %>
    <% @company.products.each do |product| %>
    <% product.errors.full_messages_for(:product_name).each do |message| %>
      <div class="text-danger"><%= message %></div>
      <% end %>
    <% end %>
  </div>

  
  <div>
    <%= form.label :Price %><br>
    <%= form.number_field :price %>
     <% @company.products.each do |product| %>
    <% product.errors.full_messages_for(:price).each do |message| %>
      <div class="text-danger"><%= message %></div>
      <% end %>
    <% end %>
  </div>

  <div class="mt-3">
    <%= form.submit "Create",class:"btn btn-outline-primary" %>
  </div>
 <% end %>

app/views/products/show.html.erb
<div class="card">
  <div class="card-header p-0">
    <h3 class="card-title mb-0">Produts_Deatiles </h3>
  </div>

  <style>
    table {
/*    border: 1px solid black;*/
    }
  </style>

  <div class="card-body p-0">
    <table class="table table-hover table-sm mb-0">
      <tbody>
      <div>
        <tr>
        <th><strong>Product_name:</strong></th>
        <td> <%= @product.product_name%></td>
        </tr>
      </div>

      <div>
        <tr>
        <th><strong>Price:</strong></th>
        <td><%=@product.price %></td>
        </tr>
      </div>
      </tbody>
    </table>
  </div>

  <div class="card-footer p-0">
    <div>
    <%= link_to "Edit",edit_company_product_path(@company,@product),class:"btn btn-outline-success" %>
    <%= link_to "Back",company_products_path(@company,@product),class: "btn btn-outline-primary" %>
    </div>


    <div class="mt-1">
    <%= link_to "Delete", company_product_path(@company,@product), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?" },class:"btn btn-outline-danger" %>
    </div>

    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
</div>
</div>